### ISSUE TITLE
UpdateValset should normalize power as a percentage

### ISSUE THREAD

**Issue by alpe** [althea-net/peggy#10]
The total power is not fix on cosmos-sdk. Validators may receive delegations or get jailed so that the threshold needs to be updated as well in [Peggy.sol](https://github.com/althea-net/peggy/blob/master/solidity/contracts/Peggy.sol#L197)

Disclaimer: first time I looked at a solidity contract so I may got it wrong how state is persisted

**Comment by jkilpatr** [comment]
This is correct.

The solution we are thinking of right now is to have the Valset process normalize all power as a percentage between 0 and some cap value. For example (2^256 - 1)(for uint256 max on Ethereum). This does increase the computation complexity and leaves some integer rounding errors to think about.

**Comment by jtremback** [comment]
The contract doesn't need to know anything about the normalization.

**Comment by alpe** [comment]
This was implemented on the cosmos side
