### ISSUE TITLE
Uint256 vs Uint64

### ISSUE THREAD

**Issue by jtremback** [althea-net/peggy#100]
Uint256's from Ethereum seem to just be turned into Uint64's in the Go module without much thought. This is definitely ripe for a vulnerability.

**Comment by jtremback** [comment]
Was just reminded that Cosmos uses BigInts. It should be able to represent anything. Use of uint64 appears to purely be an error in that case.

**Comment by jkilpatr** [comment]
Talked to zaki on this subject the actual coin amounts are bigints, so in theory this shouldn't be an issue. We should bring across the coin resolution from the ERC20 contract.

**Comment by jtremback** [comment]
I will do a fix for this across the codebase in a separate PR once I have finished #92. 

I don't think we can normalize, because amounts near the bottom of the uint256 range (a few billion etc) will be equal to zero if normalized to uint64 (I'm assuming that "normalization" here means that maxuint256 == maxuint64, e.g. divide everything by 2^(256-64)).

If we do not normalize (it looks like we are not normalizing now), then it will be possible to overflow the uint64 on the Cosmos side easily from Ethereum. I'm not sure what the behavior of Cosmos's uint64 implementation is when overflowed.

If it panics, it will be trivial to halt Cosmos by sending one Eth transaction.
If it saturates, then deposits of certain ERC20's will simply be lost.
If it wraps around, then deposits of certain ERC20's will simply be lost.
If it errors out, then deposits of certain ERC20's will simply be lost.

I think there are also other vulnerabilities that might require several steps and while it might be fun to think of some of them, it will be much faster to simply use the `sdk.Int` type which was specifically chosen to be able to represent high-precision tokens from other chains like Ethereum.

I also think that

**Comment by jkilpatr** [comment]
fixing this seems to have been delayed until the stargate update is in.

**Comment by jackzampolin** [comment]
I think the PR to do stargate substantially fixes this issue by making the amount in `ERC20Token` an `sdk.Int`
