### ISSUE TITLE
Low-level bitshifting prefix iteration code

### ISSUE THREAD

**Issue by jtremback** [althea-net/peggy#111]
We are using this code (currently at the bottom of keeper.go) as part of our prefix iteration:

```golang
// prefixRange turns a prefix into a (start, end) range. The start is the given prefix value and
// the end is calculated by adding 1 bit to the start value. Nil is not allowed as prefix.
// 		Example: []byte{1, 3, 4} becomes []byte{1, 3, 5}
// 				 []byte{15, 42, 255, 255} becomes []byte{15, 43, 0, 0}
//
// In case of an overflow the end is set to nil.
//		Example: []byte{255, 255, 255, 255} becomes nil
func prefixRange(prefix []byte) ([]byte, []byte) {
	if prefix == nil {
		panic("nil key not allowed")
	}
	// special case: no prefix is whole range
	if len(prefix) == 0 {
		return nil, nil
	}

	// copy the prefix and update last byte
	end := make([]byte, len(prefix))
	copy(end, prefix)
	l := len(end) - 1
	end[l]++

	// wait, what if that overflowed?....
	for end[l] == 0 && l > 0 {
		l--
		end[l]++
	}

	// okay, funny guy, you gave us FFF, no end to this range...
	if l == 0 && end[0] == 0 {
		end = nil
	}
	return prefix, end
}
```

Not sure how comfortable I am with using all these bit shifting hacks as a key part of our security. We should switch to some standardized method. @jackzampolin what is usually used in the Cosmos world?

**Comment by jtremback** [comment]
Not sure if this works with sdk.Ints either...

**Comment by alpe** [comment]
This code was used in [weave](https://github.com/iov-one/weave) already for range queries and got audited. Though it is fair to bring some attention to this and have all concerns addressed for production.
Range queries are a powerful feature that is not available in the sdk out of the box.

Can you elaborate how this is connected to sdk.Ints? This code is about a []byte prefix.

**Comment by jkilpatr** [comment]
@alpe  did weave do any studies on how much gas this saves?

On one hand it is pretty useful, on the other hand simplicity is nice.

**Comment by jtremback** [comment]
@jackzampolin I think you might have said the other day that this code in fact is the standard way to do this? If this is the case then we should just keep it i guess.

**Comment by alpe** [comment]
> @alpe did weave do any studies on how much gas this saves?

The intention for a range query was not to save gas but make use of the iterator functionality in the IAVL tree. If you structure your store keys for a range query in mind then you may not need a second index which then saves you a good amount of complexity and gas as a nice side effect.

**Comment by jtremback** [comment]
@alpe All numbers on the Ethereum side are uint256's. So, the most natural thing to turn them into is sdk.Int (which wrap BigInts). This was of critical importance for token balances, but we have established that it is not necessary for nonces. I assume that it would not be possible to iterate over an sdk.Int in this way because it is not fixed length. That's what the sdk.Int reference was about.

**Comment by jtremback** [comment]
It seems that this code is audited, and it is the best way to iterate over nonces for now, so I will close this issue.
