### ISSUE TITLE
Remaining big functionality to be discussed and implemented

### ISSUE THREAD

**Issue by jtremback** [althea-net/peggy#117]
1. Key delegation for the Eth Signer

2. Slashing

3. Use of uint64 for nonces discussion (just have to prove it's secure)

**Comment by jtremback** [comment]
@jkilpatr @jackzampolin

**Comment by jackzampolin** [comment]
### 1. Key Delegation for the ETH signer
It looks like there is some confusion in the code between `sdk.ValAddress` and `sdk.AccAddress` that should be cleared up as part of this refactor, but the core issue is that all ETH signer txs going to the cosmos chain currently need to be signed by the `sdk.ValAddress` of the validator. This ties a key that should be kept offline to an online process. So to solve this we either need to sign the messages with the ETH key, or enable key delegation in the peggy module to enable validators to set which `sdk.AccAddress` they sign their messages with

### 2. Slashing
Where should we slash? How much?

### 3. NoncesIs there any circumstance where

**Comment by jackzampolin** [comment]
Genesis import and export (i.e. exporting any peggy state that needs to be saved and reimporting it) is also another big TODO.

**Comment by jtremback** [comment]
@jackzampolin you had proposed having the Eth signer just use their Eth key to sign stuff for Cosmos as well. Any more thoughts on this?

**Comment by jackzampolin** [comment]
After looking at the `terra-project/core/x/oracle` stuff it might not be too hard to add key delegation for the cosmos side so for making this conceptually simple I think signing these messages with a cosmos account key would be best. Interested in having this convo in more detail today tho

**Comment by jkilpatr** [comment]
#42 is probably useful to start plotting out slashing conditions.

**Comment by jtremback** [comment]
#42 has a lot of assumptions that no longer hold with the current code. However it is probably good to go through to get ideas.

**Comment by jtremback** [comment]
Nonces are probably safe as is.
