### ISSUE TITLE
Bootstrapping process for keys

### ISSUE THREAD

**Issue by jkilpatr** [althea-net/peggy#12]
See issue #11 once we expand this message to set both eth and cosmos keys we then need to ensure that no other peggy messages are valid until such a time that 70% (ish) of validators have bothered to set their keys.

**Comment by jtremback** [comment]
Unless I misunderstand this issue, it seems that this is part of the broader bootstrapping process. My feeling is that a Peggy contract that was deployed with an incomplete valset will be seen as illegitimate by the users anyway.
