### ISSUE TITLE
Early transaction batch logic

### ISSUE THREAD

**Issue by jkilpatr** [althea-net/peggy#14]
This issue may need to be broken up into several sub-issues. It's called 'early' logic because we're definitely missing some details that will have to be added in as we test the code and refine the process. 

* When someone sends MsgSendToEth it should create an entry in the 'peggy bridge tx pool' this pool is in the Cosmos chain store and contains all transactions not yet bridged. Funds are then burned from the users account.
* The tx pool should be visible to the orchestrator using an RPC endpoint
* Someone (permissionlessly) sends a MsgRequestBatch, this produces a new batch in the 'batch store' on chain. Batches have a max size that is a constant (start with 100). Transactions are selected highest fee to lowest fee and must be of the same denom.
* The list of batches in the batch store and their contents should also be available over RPC
* The orchestrators see these batches, and submit a MsgConfirmBatch containing their signature
* Once enough signatures are collected (66% of voting power) orchestrators collect these signatures from the RPC endpoint, assemble an Ethereum transaction and submit the batch.  
* After the batch has been accepted on the Ethereum side orchestrators can send MsgBatchInChain, once 66% of all voting power has confirmed the batch the batch is marked as complete in the store and everything is finished.
* TODO consider the 'batch not submitted case' more carefully. Transactions need to either time out (issuing funds back to the sender) or be re-released into the tx pool at some point. 
    * We could just implicitly release a batch back to the pool if a MsgBatchInChain occurs for a later nonce. Lets just say that batches 1,2,3 get created. Then MsgBatchInChain passes only for 3. 1 and 2 should have their transactions moved back into the pool because it is now impossible to submit them.  This leads to some questionable logic requirements in the orchestrator. Lets say batches 2 and 3 get into the same block! now the orchestrator must be careful to ensure that MsgBatchInChain is completed for batch 2 before starting it for batch 3.

**Comment by jkilpatr** [comment]
@alpe  this is the bulk of the Cosmos sdk logic we need written for the September demo milestone. Lets spend some time refining it here before work is started on the implementation.

**Comment by alpe** [comment]
Thanks Justin for writing this down! The process is mostly clear to me now.

> When someone sends MsgSendToEth it should create an entry in the 'peggy bridge tx pool' this pool is in the Cosmos chain store and contains all transactions not yet bridged. Funds are then burned from the users account.

Do I assume correct that the `Coins` used in the message for amount and fee fields are the vouchers that point to a single contract on the ETH side and are no native cosmos chain token?

> The tx pool should be visible to the orchestrator using an RPC endpoint
I would propose some types unless you have something in your mind already. 

> Someone ... Transactions are selected highest fee to lowest fee and must be of the same denom.

I need to understand the relation of peggy -> Eth contract ->tokens better. I assume 1-to-1-to-1 for now

> Once enough signatures are collected (66% of voting power) orchestrators collect these signatures from the RPC endpoint, assemble an Ethereum transaction and submit the batch.


I am not sure if we can expect that the current valSet is already present in the contract. So there is a chance that the Tx fails on the contract side unless we check against the last (successfully) submitted valSet.
Adding a +x buffer to the threshold here may help a bit but gives no guarantees. See #16 // cc @ethanfrey 

Currently there is no state persisted on the cosmos side for threshold reached in the update valSet process. I think we should be clear on the conditions for the state transfer and build this into the peggy module. This would reduce the complexity on the client side a lot.

> ... once 66% of all voting power has confirmed the batch the batch is marked  as complete in the store and everything is finished.

Good to have this step! Is there any cleanup in the data that we can do in this step that you have in your mind already?

**Comment by ethanfrey** [comment]
This is a good write up.

I would propose having all this design info in a markdown file in the repo. I will start tackling #7 and incorporate much of this (and notes.md)

**Comment by jkilpatr** [comment]
> Do I assume correct that the `Coins` used in the message for amount and fee fields are the vouchers that point to a single contract on the ETH side and are no native cosmos chain token?

Yes this is the case and will remain the case for our milestones this year. 




> I need to understand the relation of peggy -> Eth contract ->tokens better. I assume 1-to-1-to-1 for now

For the Steptember development target (working demo) the Eth contract is hardcoded to a single token, so yes that's a correct assumption. 



> I am not sure if we can expect that the current valSet is already present in the contract. So there is a chance that the Tx fails on the contract side unless we check against the last (successfully) submitted valSet.
> Adding a +x buffer to the threshold here may help a bit but gives no guarantees. See #16 // cc @ethanfrey
> 
> Currently there is no state persisted on the cosmos side for threshold reached in the update valSet process. I think we should be clear on the conditions for the state transfer and build this into the peggy module. This would reduce the complexity on the client side a lot.

So as @jtremback  outlined in #16 the issue on valset updates it doesn't really matter if the *current* validator set is in the contract just that more than 33% of the power has not changed since the last update. This is generally true the vast majority of the time. That being said it is a good concern to have which is why we're working on 'combined' batch relaying and updates in #15 as that solves this problem quite nicely. Although it may introduce other new ones.



> Good to have this step! Is there any cleanup in the data that we can do in this step that you have in your mind already?

We should make sure that all processed transactions are removed from both the batch store and the tx pool. This is just good practice to prevent a timeout routine or anything else from accidentally processing them twice and creating a double withdraw.

**Comment by alpe** [comment]
The cosmos side was implemented except for 
>TODO consider the 'batch not submitted case' more carefully.  ...

and data cleanup. Which both should go into a post MVP release. How do we proceed with this issue? @jkilpatr ?
