### ISSUE TITLE
Prevent lock out from contract

### ISSUE THREAD

**Issue by alpe** [althea-net/peggy#16]
In order to authenticate and authorize a message the ETH contract has a [hash persisted](https://github.com/althea-net/peggy/blob/master/solidity/contracts/Peggy.sol#L167) that is rebuilt by message parameters. 
This is a smart and efficient way to save gas on the ETH side but makes it fragile as the ValSet data is dynamic on the cosmos side. 
An update to the ETH contract will take some time to be trusted (no fork) and we may also not want to propagate any valSet update immediately to work cost effective.
During this period the "current" valSet is not correct as it was modified and we can not do any further operations with the contract.
Instead we need to send the "last submitted" valSet which can not clearly be identified without a feedback process from ETH to cosmos.
It could be the "last" (orchestrator) "confirmed" valSet in store but there is no guarantee nor a way to recover from this automatically.

**Comment by jkilpatr** [comment]
This is a valid design issue.

So far my assumption has been that it's the job of the Orchestrator to ensure that the validator set gets updated in an emergency situation.

During normal operation on a chain like the hub validator sets don't actually change that much very often. But in the case of a sudden change it's up to slashing conditions to ensure the old validator set signs off on the chain and any one honest orchestrator to make sure the contract gets updated.

Obviously there are worst case scenarios. Where the ETH chain is effectively halted due to some big activity event during a major Cosmos validator set change. In that case it's up to the slashing conditions to ensure that a trail of validator set updates exists for the Orchestrator to play back when possible.

**Comment by jtremback** [comment]
1. @alpe I'd be interested if you could illustrate an attack or malfunction that could result from this?

**Comment by jtremback** [comment]
> In order to authenticate and authorize a message the ETH contract has a hash persisted that is rebuilt by message parameters.
> This is a smart and efficient way to save gas on the ETH side but makes it fragile as the ValSet data is dynamic on the cosmos side.

This overall issue you raise is valid, but I'm not sure the hashing storage trick has anything to do with it. It would be an issue as well if we simply stored the valset in the contract in full, no?

> An update to the ETH contract will take some time to be trusted (no fork) and we may also not want to propagate any valSet update immediately to work cost effective.
> During this period the "current" valSet is not correct as it was modified and we can not do any further operations with the contract.

As we've written in notes.md, there is a parameter "EthBlockDelay" which everyone agrees that Ethereum state is final after. For instance, this might be 50 Ethereum blocks. I will use 50 blocks in the rest of this comment. So, our design assumes that Ethereum has finality, but also latency. Any issues which come about as a result of Ethereum's lack of finality can be viewed as issues of latency.

> Instead we need to send the "last submitted" valSet which can not clearly be identified without a feedback process from ETH to cosmos.

We have a feedback process from ETH to Cosmos. The validators, and everyone else, agree completely on the state of Ethereum 50 blocks ago. So anyone who wants to submit a new valset will know exactly which signatures it needs, but will have to wait at least 50 blocks after the last valset was submitted.

This defines the issue more clearly: What scenarios exist where a 50 block delay of valset submission causes a problem? Justin hints at one:

> Obviously there are worst case scenarios. Where the ETH chain is effectively halted due to some big activity event during a major Cosmos validator set change. In that case it's up to the slashing conditions to ensure that a trail of validator set updates exists for the Orchestrator to play back when possible.

**Comment by jtremback** [comment]
It's also important to keep in mind that you don't need all validator signatures, just 2/3s of them. In most scenarios, a valset would be accepted by the contract if it just had signatures from the current valset, not the one in the contract!

So, in principle, there will only be a problem if the valset changes by more than 1/3 during "EthBlockDelay" blocks. I'm not an expert on Tendermint, but I'm guessing that there are very few such scenarios which do not also result in a chain halt on the Cosmos side. 

That being said, it's still bad if all the tokens are stuck in the bridge after a chain halt, but I'm not convinced that is a problem we should try to solve.

**Comment by alpe** [comment]
Thanks for the feedback on the issues. Good discussions! 💐 

> ... but I'm not sure the hashing storage trick has anything to do with it.

The same issue would arise with the full valSet stored when processing a message. But for a recovery process we could read the state from the contract and provide the correct data in a new message. Though the interface can look different so this is all hypothetical... and not what I had in mind.

> We have a feedback process from ETH to Cosmos. 

I have not found it in the code/ issues. If we get oracle attestations for the valSet update as well we can persist the proper contract state in cosmos and prevent inflight updates. This is all I ask for right now and that would make me very happy! 😄  

> Do we need to have knowledge of the current contract validator state on chain in order to facilitate any useful slashing conditions?

Depends on the slashing conditions and where it happens. On the cosmos side we would need an oracle to find out a msg was not relayed (in time/ blocks). On the ETH contract side enough information may be available already when the sequence is higher than expected. But who to slash? Missing signatures can be detected on both sides but the valSet may not be fully up to date on the contract side.

> So, in principle, there will only be a problem if the valset changes by more than 1/3 during "EthBlockDelay" blocks...

Definitively a problem. Let's add a task for a future version. A graceful fade out scenario for example to allow a validator to be removed from the valSet in the ETH contract while they still participate in cosmos for a while.... but there is also the unhappy scenario

> The one place this might be a realistic issue is that 1/3 of the validators could get together and blackmail everyone,

Let's add a task and at least prepare a fallback idea for the worst case scenario to unlock the tokens in the contract. Like a dead man switch with a hard coded multisig address.... and be transparent about this and why.

**Comment by jkilpatr** [comment]
> I have not found it in the code/ issues. If we get oracle attestations for the valSet update as well we can persist the proper contract state in cosmos and prevent inflight updates. This is all I ask for right now and that would make me very happy! smile

I'm fine with this, it's a minimal amount of work since it follows the same pattern as all our other oracle actions. 



> Let's add a task and at least prepare a fallback idea for the worst case scenario to unlock the tokens in the contract. Like a dead man switch with a hard coded multisig address.... and be transparent about this and why

this is also a reasonable task.

**Comment by jtremback** [comment]
> I have not found it in the code/ issues. If we get oracle attestations for the valSet update as well we can persist the proper contract state in cosmos and prevent inflight updates. This is all I ask for right now and that would make me very happy!

This is mostly because we haven't written much down lol. But the Cosmos state machine will contain full knowledge of Eth, but with some delay as I wrote above.

> Let's add a task and at least prepare a fallback idea for the worst case scenario to unlock the tokens in the contract. Like a dead man switch with a hard coded multisig address.... and be transparent about this and why.

I am strongly opposed to this. If we do this, there is absolutely no point in doing anything other than a fully custodial bridge, like wBTC or XDai.

**Comment by alpe** [comment]
> I am strongly opposed to this.

I am not going to push a solution here. It is a risk that we need to address or document proper.

**Comment by jtremback** [comment]
I agree we need to document the risk. I also think we should probably have someone with a deep understanding of the Tendermint/Cosmos consensus and staking model look at it and help us quantify the situations where the bridge could plausibly be frozen by a large outgoing validator that has already been slashed.

**Comment by alpe** [comment]
>...  quantify the situations where the bridge could plausibly be frozen by a large outgoing validator that has already been slashed.

If there is a risk that one validator holds >33% of the power then this is not a healthy setup. IMHO we can not do much about this unless we can change the threshold value in the contract.

**Comment by jtremback** [comment]
I think we agree on this, but my assumption is that if >33% of the Cosmos validator power is rebelling, then the chain as a whole has big problems that go beyond peggy.

**Comment by jkilpatr** [comment]
This issue will be addressed post MVP
