### ISSUE TITLE
Prevent conflicts in token denominator 

### ISSUE THREAD

**Issue by alpe** [althea-net/peggy#17]
We are in a similar situation as IBC when we import ETH tokens into cosmos as "vouchers". 
In order to prevent name conflicts we can copy their approach and store a `peggy/<hash>` denominator instead. "peggy" would be the namespace we claim. The hash could be build from the ETH **contract address** and the **ETH token**.  So technically we should be able to support multiple contracts and tokens on the cosmos side.

See IBC impl: https://github.com/cosmos/cosmos-sdk/blob/master/x/ibc-transfer/keeper/relay.go#L92

**Comment by jkilpatr** [comment]
I'm fine with this as a design implementation, it may be useful to have some way to store a 'human readable name'. That way it's possible to have tokens with colliding 'human readable' names without serious security issues.

**Comment by alpe** [comment]
> ... it may be useful to have some way to store a 'human readable name'. 
Completely agree. This would be very helpful for any UI.

**Comment by alpe** [comment]
This implemented and stored as `BridgedDenominators`.

```go
// BridgedDenominator track and identify the ported ERC20 tokens into Peggy.
// An ERC20 token on the Ethereum side can be uniquely identified by the ERC20 contract address and the human readable symbol
// used for it in the contract
// In Peggy this is represented as "vouchers" that get minted and burned when interacting with the Ethereum side. These "vouchers"
// are identified by a prefixed string representation. See VoucherDenom type.
type BridgedDenominator struct {
	// TokenContractAddress is the ERC20 contract address
	TokenContractAddress EthereumAddress `json:"token_contract_address"`
	// Symbol is the human readable ERC20 token name.
	Symbol string `json:"symbol"`
	// CosmosVoucherDenom is used as denom in sdk.Coin
	CosmosVoucherDenom VoucherDenom `json:"cosmos_voucher_denom"`
}
```

* CLI query
`peggycli q peggy all-bridged-denominators`
