### ISSUE TITLE
REST endpoint that grabs all ValsetConfirmations for a given height

### ISSUE THREAD

**Issue by jkilpatr** [althea-net/peggy#3]
This is an ergonomics issue, the current endpoint only does this for one validator at a time. 

This endpoint 

https://github.com/althea-net/peggy/blob/master/module/x/peggy/client/rest/query.go#L53

Is used to get signatures for validator set updates as submitted by the orchestrator. Right now the orchestrator will have to guess the correct block height and then iterate over all the validators

This endpoint should be re-defined and split into two. One endpoint that gets the latest Valset for which any signatures have been submitted and displays that. And another which allows requesting specific nonces (which are the same as block heights). 

A third endpoint, which indicates all valid block heights for which validator set requests exist would also be quite nice.

**Comment by ethanfrey** [comment]
Please label this "REST" endpoint to mean the rest server running on 1337. "RPC" generally means tendermint's json-rpc server (26657).

A bit a nitpicky, but clarity is good. Also can you link to the current code that does for one at a time?

**Comment by jtremback** [comment]
This is intentional. The contract requires signatures from the contract's last valset, not the current valset. So the only way to make this convenience endpoint would be to have the module have knowledge of the contract state. Of course, it will have knowledge of Ethereum for other reasons, but it seemed overly complicated to use it here.

**Comment by alpe** [comment]
> And another which allows requesting specific nonces (which are the same as block heights).
I can return the confirmations but you would not know if they exceeded the threshold. Can you elaborate a bit on the use case of the orchestrate, please? I do understand that this would definitively make sense for safety and fallback scenarios.

> One endpoint that gets the latest Valset for which any signatures have been submitted and displays that...

As @jtremback pointed out:
> The contract requires signatures from the contract's last valset, not the current valset 

This is a bigger issue that I highlighted in #16 and that we need to address proper.
I can build a quick hack for our test environment were we fallback to the last valSet that had reached enough confirmations. But it is an ugly hack and expensive as the Valset in cosmos is stateless right now.


> A third endpoint, which indicates all valid block heights for which validator set requests exist would also be quite nice.

I understand the motivation for this to support the first query function but I would like to understand the bigger picture better. Right now I assume the following states are possible
A pending valUpdate  exists
1) without enough signatures to succeed (deprecated by a new request)
2) without enough signatures to succeed, yet (but still open for confirmations)
3) with enough signatures and not submitted, yet (and not deprecated by a new request)
4) with enough signatures and submitted (successfully)
5) with enough signatures and submitted (failed on ETH side for whatever reason)

The orchestrator could look for 3) to submit and needs 4) for the "current" valSet. But we don't have enough information in the cosmos module to answer them proper.

**Comment by ethanfrey** [comment]
We definitely need a better design doc than the current notes.md and various hand-written notes I have from the meetings.

Most of this can be argued in pseudocode and specs before we write anymore code (although those msg structs are useful to discuss and great to include in a spec)

**Comment by jkilpatr** [comment]
@alpe  

you are correct about the possible states a validator set update could be in. With that and @jtremback 's words in mind we should probably just make the second endpoint (one that lists all validator set requests, leaving it up to the orchestrator to go through and figure out which one to use)

**Comment by jkilpatr** [comment]
@alpe  this issue is blocking for me mostly because I can't move forward with the valSetUpdate flow in test until this endpoint works. https://github.com/althea-net/peggy/blob/master/module/x/peggy/client/rest/query.go#L50

Right now it's broken for very dumb reasons (mainly things I don't understand about how the store works)

**Comment by jkilpatr** [comment]
Please review this pull request https://github.com/althea-net/peggy/pull/34

It's hardly complete but it does outline the problem well. We need an easy way for a querier to figure out what valset requests are available and who signed them without having to have outside info.
