### ISSUE TITLE
Ethereum Oracle

### ISSUE THREAD

**Issue by jtremback** [althea-net/peggy#31]
There has been some confusion in other issues about how exactly the Cosmos state machine gets knowledge of what's going on on Ethereum, so I figured I'd write up our current thinking from notes.md and we can sort it all out here.

First of all, I believe that implementation and discussion of other parts of the Cosmos module will be clearer if they can just assume that they have all the information they need from the Ethereum state. Then we won't need to write down the steps of getting this state as part of the documentation for other processes, and other parts of the code can just load the state they need from the KV store when they need it. The question of exactly which Ethereum state we need is an implementation detail.

Second, I'd just like to point out a quick detail: In some other issues, Ethereum light clients have been mentioned. We will not be using a light client. One of the benefits of Cosmos is that arbitrary code can be run on the validators, and in our case, we will make them run an Ethereum full node.

So here's the current thinking from notes.md:

### First version where our logic handles submission of Ethereum state into the Cosmos state machine, as well as determining when enough validators have signed off on it.

- There is a governance parameter called EthBlockDelay, for example 50 blocks
- The orchestrator binary on each validator gets the current block number from their Geth, then gets the data we are interested in from the block EthBlockDelay lower than the current one. For example: https://geth.ethereum.org/docs/rpc/ns-eth
- They send an EthBlockData message
- These messages go in an EthBlockDataStore, indexed by the block number and the validator that sent them.
- Once there is a version of the block data that matches from at least 66% of the validators (the current validators in power on the Cosmos chain, not the last valset in the contract), it is considered legit. For example, another part of the code might mint some tokens in Cosmos based on tokens sent into the Peggy contract.
- (optional downtime slashing???) Something watches for validators that have not submitted matching block data, and triggers a downtime slashing

This version will result in a lot of messages being sent into Cosmos. I also wonder if it is messy/risky for us to handle the logic around whether a given block's data is accepted by 66% percent of the validators. Perhaps there is a way for us to kick that decision down to the underlying Tendermint consensus. I will cover it in the next variation.

### Alternate version- "Ethereum state injection"

- Each validator machine has a multi-process key value store (which is entirely distinct from the KV store in the Cosmos state). It is called the "Eth state store"
- The orchestrator binary on each validator gets the current block number from their Geth, then gets the data we are interested in from the block EthBlockDelay lower than the current one. For example: https://geth.ethereum.org/docs/rpc/ns-eth
- Instead of sending a Cosmos message like the previous scheme, they load the Ethereum state for each block directly into their local Eth state store.
- The Cosmos state machine being run by each validator calls a library which accesses the local Eth state store. Data about the contract comes from this. This may seem bad because you are not supposed to use non-deterministic code in the Cosmos state machine. However, the data in the Eth state store is only non deterministic if a validator does not have the same view of Ethereum as the others. So, instead of our logic manually checking for 66% of the signatures and manually slashing for downtime if someone does not agree, this logic is all handled by the underlying Tendermint consensus.

This second method has one big downside: If there is a major problem on the Ethereum chain, it could halt the whole consensus process. In the first method, a major Ethereum issue will ever halt the bridge. Another practical issue is that the second method will be more complicated to implement. For these reasons, I think we've basically decided to pursue the first method for now.

**Comment by jkilpatr** [comment]
> One of the benefits of Cosmos is that arbitrary code can be run on the validators, and in our case, we will make them run an Ethereum full node.

I don't think you present a compelling argument why this is *required* a light client can verify proofs and should provide the same security at a higher latency.

**Comment by jtremback** [comment]
I think the advantage of using full nodes instead of a light client here is ease of implementation.

**Comment by jtremback** [comment]
I've added the first scheme to overview.md, since this seems to be the most promising direction https://github.com/althea-net/peggy/pull/32/files
