### ISSUE TITLE
Failure running tests

### ISSUE THREAD

**Issue by RhettCreighton** [althea-net/peggy#38]
status: exit code: 1
stdout: 
stderr: ⨯ Unable to compile TypeScript:
contract-deployer.ts(1,23): error TS2307: Cannot find module './typechain/Peggy' or its corresponding type declarations.
contract-deployer.ts(2,27): error TS2307: Cannot find module './typechain/TestERC20' or its corresponding type declarations.
contract-deployer.ts(3,24): error TS2307: Cannot find module 'ethers' or its corresponding type declarations.
contract-deployer.ts(4,16): error TS2307: Cannot find module 'fs' or its corresponding type declarations.
contract-deployer.ts(5,29): error TS2307: Cannot find module 'command-line-args' or its corresponding type declarations.
contract-deployer.ts(6,70): error TS2307: Cannot find module 'axios' or its corresponding type declarations.
contract-deployer.ts(37,16): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
contract-deployer.ts(84,50): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
contract-deployer.ts(90,16): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
contract-deployer.ts(92,16): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.

Following the readme after I run this:

./tests/run-tests.sh

Here are the logs from the server tab

+ GAIA_HOME='--home /validator3'
+ LISTEN_ADDRESS='--address tcp://7.7.7.3:26655'
+ RPC_ADDRESS='--rpc.laddr tcp://7.7.7.3:26657'
+ P2P_ADDRESS='--p2p.laddr tcp://7.7.7.3:26656'
+ LOG_LEVEL='--log_level *:error'
+ ARGS='--home /validator3 --address tcp://7.7.7.3:26655 --rpc.laddr tcp://7.7.7.3:26657 --p2p.laddr tcp://7.7.7.3:26656 --log_level *:error'
+ sleep 10
+ peggycli rest-server --laddr tcp://0.0.0.0:1317 --trust-node --node tcp://7.7.7.1:26657
+ peggyd --home /validator3 --address tcp://7.7.7.3:26655 --rpc.laddr tcp://7.7.7.3:26657 --p2p.laddr tcp://7.7.7.3:26656 --log_level '*:error' start
I[2020-09-15|03:55:40.206] Starting application REST service (chain-id: "")... module=rest-server 
I[2020-09-15|03:55:40.206] Starting RPC HTTP server on [::]:1317        module=rest-server 
E[2020-09-15|03:55:40.252] Profile server                               module=node err="listen tcp 127.0.0.1:6060: bind: address already in use"
E[2020-09-15|03:55:40.254] dialing failed (attempts: 1): dial tcp 7.7.7.3:26656: connect: connection refused module=pex addr=55f512082f35b041b91263286cddd82093a30158@7.7.7.3:26656
E[2020-09-15|03:55:40.256] Profile server                               module=node err="listen tcp 127.0.0.1:6060: bind: address already in use"
+ sleep 10
+ bash /peggy/tests/container-scripts/run-eth.sh
INFO [09-15|03:55:50.056] Maximum peer count                       ETH=50 LES=0 total=50
INFO [09-15|03:55:50.057] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
ERROR[09-15|03:55:50.057] Failed to enumerate USB devices          hub=ledger vendor=11415 failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[09-15|03:55:50.057] Failed to enumerate USB devices          hub=trezor vendor=21324 failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[09-15|03:55:50.057] Failed to enumerate USB devices          hub=trezor vendor=4617  failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[09-15|03:55:50.057] Failed to enumerate USB devices          hub=ledger vendor=11415 failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[09-15|03:55:50.058] Failed to enumerate USB devices          hub=trezor vendor=21324 failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[09-15|03:55:50.058] Failed to enumerate USB devices          hub=trezor vendor=4617  failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"
INFO [09-15|03:55:50.058] Allocated cache and file handles         database=/root/.ethereum/geth/chaindata cache=16.00MiB handles=16
INFO [09-15|03:55:50.063] Writing custom genesis block 
INFO [09-15|03:55:50.063] Persisted trie from memory database      nodes=1 size=150.00B time="49.495µs" gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [09-15|03:55:50.064] Successfully wrote genesis state         database=chaindata                      hash="de13e3…eeddea"
INFO [09-15|03:55:50.064] Allocated cache and file handles         database=/root/.ethereum/geth/lightchaindata cache=16.00MiB handles=16
INFO [09-15|03:55:50.067] Writing custom genesis block 
INFO [09-15|03:55:50.067] Persisted trie from memory database      nodes=1 size=150.00B time="54.984µs" gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [09-15|03:55:50.067] Successfully wrote genesis state         database=lightchaindata                      hash="de13e3…eeddea"
+ read -p 'Press Return to Close...'
Press Return to Close...E[2020-09-15|03:56:40.220] dialing failed (attempts: 1): auth failure: secret conn failed: EOF module=pex addr=55f512082f35b041b91263286cddd82093a30158@7.7.7.3:26656
E[2020-09-15|03:56:40.258] dialing failed (attempts: 1): auth failure: secret conn failed: EOF module=pex addr=81b48177a2a46a80d9a5ab3a5e176b3bcdcc0432@7.7.7.2:26656
I[2020-09-15|03:56:58.508] Served RPC HTTP response                     module=rest-server method=GET url=/auth/accounts/cosmos17xwyf8k99d4v27pc9jnfwtd45m3qndh9kk4jes status=200 duration=27 remoteAddr=127.0.0.1:43008
I[2020-09-15|03:56:58.516] Served RPC HTTP response                     module=rest-server method=GET url=/blocks/latest status=200 duration=4 remoteAddr=127.0.0.1:43008
I[2020-09-15|03:57:03.832] Served RPC HTTP response                     module=rest-server method=POST url=/txs status=200 duration=5159 remoteAddr=127.0.0.1:43008
I[2020-09-15|03:57:03.886] Served RPC HTTP response                     module=rest-server method=GET url=/auth/accounts/cosmos107mu77qnndty67tjf7pftpkf00h57gxsyfmkdy status=200 duration=2 remoteAddr=127.0.0.1:43008
I[2020-09-15|03:57:03.903] Served RPC HTTP response                     module=rest-server method=GET url=/blocks/latest status=200 duration=3 remoteAddr=127.0.0.1:43008
I[2020-09-15|03:57:09.447] Served RPC HTTP response                     module=rest-server method=POST url=/txs status=200 duration=5409 remoteAddr=127.0.0.1:43008
I[2020-09-15|03:57:09.524] Served RPC HTTP response                     module=rest-server method=GET url=/auth/accounts/cosmos18p3fwzl2r2a2nnfm7pn63da6rrmhhmqzxt3gv9 status=200 duration=2 remoteAddr=127.0.0.1:43008
I[2020-09-15|03:57:09.529] Served RPC HTTP response                     module=rest-server method=GET url=/blocks/latest status=200 duration=3 remoteAddr=127.0.0.1:43008
E[2020-09-15|03:57:10.222] dialing failed (attempts: 2): auth failure: secret conn failed: EOF module=pex addr=55f512082f35b041b91263286cddd82093a30158@7.7.7.3:26656
E[2020-09-15|03:57:10.258] dialing failed (attempts: 2): auth failure: secret conn failed: EOF module=pex addr=81b48177a2a46a80d9a5ab3a5e176b3bcdcc0432@7.7.7.2:26656
I[2020-09-15|03:57:15.081] Served RPC HTTP response                     module=rest-server method=POST url=/txs status=200 duration=5407 remoteAddr=127.0.0.1:43008
I[2020-09-15|03:57:15.163] Served RPC HTTP response                     module=rest-server method=GET url=/auth/accounts/cosmos17xwyf8k99d4v27pc9jnfwtd45m3qndh9kk4jes status=200 duration=3 remoteAddr=127.0.0.1:43008
I[2020-09-15|03:57:15.169] Served RPC HTTP response                     module=rest-server method=GET url=/blocks/latest status=200 duration=3 remoteAddr=127.0.0.1:43008
I[2020-09-15|03:57:20.625] Served RPC HTTP response                     module=rest-server method=POST url=/txs status=200 duration=5337 remoteAddr=127.0.0.1:43008
Query for  18 18
I[2020-09-15|03:57:20.629] Served RPC HTTP response                     module=rest-server method=GET url=/peggy/valset_request/18 status=200 duration=1 remoteAddr=127.0.0.1:43008
I[2020-09-15|03:57:20.707] Served RPC HTTP response                     module=rest-server method=GET url=/auth/accounts/cosmos17xwyf8k99d4v27pc9jnfwtd45m3qndh9kk4jes status=200 duration=2 remoteAddr=127.0.0.1:43008
I[2020-09-15|03:57:20.712] Served RPC HTTP response                     module=rest-server method=GET url=/blocks/latest status=200 duration=3 remoteAddr=127.0.0.1:43008
I[2020-09-15|03:57:26.264] Served RPC HTTP response                     module=rest-server method=POST url=/txs status=200 duration=5396 remoteAddr=127.0.0.1:43008
I[2020-09-15|03:57:26.345] Served RPC HTTP response                     module=rest-server method=GET url=/auth/accounts/cosmos107mu77qnndty67tjf7pftpkf00h57gxsyfmkdy status=200 duration=2 remoteAddr=127.0.0.1:43008
I[2020-09-15|03:57:26.365] Served RPC HTTP response                     module=rest-server method=GET url=/blocks/latest status=200 duration=3 remoteAddr=127.0.0.1:43008
I[2020-09-15|03:57:32.011] Served RPC HTTP response                     module=rest-server method=POST url=/txs status=200 duration=5528 remoteAddr=127.0.0.1:43008
I[2020-09-15|03:57:32.093] Served RPC HTTP response                     module=rest-server method=GET url=/auth/accounts/cosmos18p3fwzl2r2a2nnfm7pn63da6rrmhhmqzxt3gv9 status=200 duration=3 remoteAddr=127.0.0.1:43008
I[2020-09-15|03:57:32.100] Served RPC HTTP response                     module=rest-server method=GET url=/blocks/latest status=200 duration=3 remoteAddr=127.0.0.1:43008
I[2020-09-15|03:57:37.585] Served RPC HTTP response                     module=rest-server method=POST url=/txs status=200 duration=5325 remoteAddr=127.0.0.1:43008
E[2020-09-15|03:57:40.222] dialing failed (attempts: 3): auth failure: secret conn failed: read tcp 7.7.7.3:50846->7.7.7.3:26656: read: connection reset by peer module=pex addr=55f512082f35b041b91263286cddd82093a30158@7.7.7.3:26656
E[2020-09-15|03:57:40.259] dialing failed (attempts: 3): auth failure: secret conn failed: EOF module=pex addr=81b48177a2a46a80d9a5ab3a5e176b3bcdcc0432@7.7.7.2:26656
E[2020-09-15|03:58:10.220] dialing failed (attempts: 4): auth failure: secret conn failed: EOF module=pex addr=55f512082f35b041b91263286cddd82093a30158@7.7.7.3:26656
E[2020-09-15|03:58:10.258] dialing failed (attempts: 4): auth failure: secret conn failed: EOF module=pex addr=81b48177a2a46a80d9a5ab3a5e176b3bcdcc0432@7.7.7.2:26656
E[2020-09-15|03:58:40.231] dialing failed (attempts: 5): auth failure: secret conn failed: read tcp 7.7.7.3:50884->7.7.7.3:26656: read: connection reset by peer module=pex addr=55f512082f35b041b91263286cddd82093a30158@7.7.7.3:26656
E[2020-09-15|03:58:40.259] dialing failed (attempts: 5): auth failure: secret conn failed: EOF module=pex addr=81b48177a2a46a80d9a5ab3a5e176b3bcdcc0432@7.7.7.2:26656
E[2020-09-15|03:59:40.222] dialing failed (attempts: 6): auth failure: secret conn failed: EOF module=pex addr=55f512082f35b041b91263286cddd82093a30158@7.7.7.3:26656
E[2020-09-15|03:59:40.258] dialing failed (attempts: 6): auth failure: secret conn failed: EOF module=pex addr=81b48177a2a46a80d9a5ab3a5e176b3bcdcc0432@7.7.7.2:26656
E[2020-09-15|04:01:10.220] dialing failed (attempts: 7): auth failure: secret conn failed: EOF module=pex addr=55f512082f35b041b91263286cddd82093a30158@7.7.7.3:26656
E[2020-09-15|04:01:10.258] dialing failed (attempts: 7): auth failure: secret conn failed: EOF module=pex addr=81b48177a2a46a80d9a5ab3a5e176b3bcdcc0432@7.7.7.2:26656

**Comment by alpe** [comment]
Thanks for reporting!
From the error message I assume `npm run typechain` in `/solidity` was not executed.

**Comment by shravanshetty1** [comment]
@alpe the solidity test works once you generate the typechain files.
However the integration tests dont work.
```
About to make contact request to blocks/latest with payload null
I[2020-09-17|13:26:20.267] Served RPC HTTP response                     module=rest-server method=GET url=/blocks/latest status=200 duration=0 remoteAddr=127.0.0.1:57978
got Cosmos JSONRPC response Ok(
    Object({
        "block": Null,
        "block_id": Object({
            "hash": String(
                "",
            ),
            "parts": Object({
                "hash": String(
                    "",
                ),
                "total": String(
                    "0",
                ),
            }),
        }),
    }),
)
thread 'main' panicked at 'Failed to update eth address!: BadResponse("invalid type: null, expected struct Block")', src/main.rs:92:14
stack backtrace:
   0:     0x55b91d89c5c5 - backtrace::backtrace::libunwind::trace::h14d338b30b3ea0a7
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x55b91d89c5c5 - backtrace::backtrace::trace_unsynchronized::h73ea91d74a3fd67f
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x55b91d89c5c5 - std::sys_common::backtrace::_print_fmt::hd42948c952866e12
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x55b91d89c5c5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha8f928866ff7571e
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55b91d8c5e0c - core::fmt::write::he0c1e5f7426d2718
                               at src/libcore/fmt/mod.rs:1076
   5:     0x55b91d896372 - std::io::Write::write_fmt::hf3afc6cfd57d0033
                               at src/libstd/io/mod.rs:1537
   6:     0x55b91d89ec70 - std::sys_common::backtrace::_print::hfc0110703f3696fd
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x55b91d89ec70 - std::sys_common::backtrace::print::h3f77c6990ddfaa22
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55b91d89ec70 - std::panicking::default_hook::{{closure}}::heae49580a8d62d75
                               at src/libstd/panicking.rs:198
   9:     0x55b91d89e9bc - std::panicking::default_hook::hecc34e3f729e213c
                               at src/libstd/panicking.rs:217
  10:     0x55b91d89f2b3 - std::panicking::rust_panic_with_hook::he82f5d0644692441
                               at src/libstd/panicking.rs:526
  11:     0x55b91d89eeab - rust_begin_unwind
                               at src/libstd/panicking.rs:437
  12:     0x55b91d8c44f1 - core::panicking::panic_fmt::h09c929f06bb87c98
                               at src/libcore/panicking.rs:85
  13:     0x55b91d8c4313 - core::option::expect_none_failed::h188f17af6c9f404b
                               at src/libcore/option.rs:1269
  14:     0x55b91d03c398 - core::result::Result<T,E>::expect::hb2341d3ef2437229
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/result.rs:963
  15:     0x55b91d04c809 - test_runner::main::{{closure}}::h23699001f2fb3c0d
                               at src/main.rs:89
  16:     0x55b91d04b0c9 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h52deeb3716ca00ef
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/future/mod.rs:78
  17:     0x55b91d02c9b6 - <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}::{{closure}}::hc503abb639bd3fc4
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/task/local.rs:528
  18:     0x55b91d04bbd6 - tokio::coop::with_budget::{{closure}}::h2fc631ba65e823b9
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:127
  19:     0x55b91d0444b1 - std::thread::local::LocalKey<T>::try_with::hd7ffcaebfbd6d224
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/thread/local.rs:263
  20:     0x55b91d043a9d - std::thread::local::LocalKey<T>::with::h0dffb1a09f51a1f9
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/thread/local.rs:239
  21:     0x55b91d02c885 - tokio::coop::with_budget::h99899f9c1d265be8
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:120
  22:     0x55b91d02c885 - tokio::coop::budget::hef31bb9645ab1ea4
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:96
  23:     0x55b91d02c885 - <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}::hb8a608f96564bf6b
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/task/local.rs:528
  24:     0x55b91cfeead6 - tokio::macros::scoped_tls::ScopedKey<T>::set::h064b8e13e75245be
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/macros/scoped_tls.rs:63
  25:     0x55b91d02c2f1 - tokio::task::local::LocalSet::with::h2f8d169949159ddf
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/task/local.rs:442
  26:     0x55b91d02c702 - <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::h2bae366d519414b1
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/task/local.rs:518
  27:     0x55b91d02c57d - tokio::task::local::LocalSet::run_until::{{closure}}::h7832d36ebc98d24f
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/task/local.rs:392
  28:     0x55b91d04b819 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hfbdee46056a09728
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/future/mod.rs:78
  29:     0x55b91cff6ab3 - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}::{{closure}}::he0c6bb5c6c0db371
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:131
  30:     0x55b91d04bcf6 - tokio::coop::with_budget::{{closure}}::h53f662ada7566203
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:127
  31:     0x55b91d0445e1 - std::thread::local::LocalKey<T>::try_with::hd829c4dd43bc7f59
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/thread/local.rs:263
  32:     0x55b91d043b0d - std::thread::local::LocalKey<T>::with::h60fc7082ef6fe789
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/thread/local.rs:239
  33:     0x55b91cff6419 - tokio::coop::with_budget::haed587eb79904f26
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:120
  34:     0x55b91cff6419 - tokio::coop::budget::h116777b533821d4a
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:96
  35:     0x55b91cff6419 - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}::h55e64a46bd474107
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:131
  36:     0x55b91cff6f70 - tokio::runtime::basic_scheduler::enter::{{closure}}::h6eaa4b3c030bf473
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:213
  37:     0x55b91cfeec0e - tokio::macros::scoped_tls::ScopedKey<T>::set::h78e852c61d270983
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/macros/scoped_tls.rs:63
  38:     0x55b91cff6e3f - tokio::runtime::basic_scheduler::enter::h7db68c36bef501a2
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:213
  39:     0x55b91cff618d - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::hd13d5253ab0eb288
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:123
  40:     0x55b91cfe9109 - tokio::runtime::Runtime::block_on::{{closure}}::h1722b5ca7f3c7923
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/mod.rs:444
  41:     0x55b91d02e7bf - tokio::runtime::context::enter::h09850aaf0ea8513d
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/context.rs:72
  42:     0x55b91d03e35a - tokio::runtime::handle::Handle::enter::h74e98c0f2d971fa5
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/handle.rs:76
  43:     0x55b91cfe907d - tokio::runtime::Runtime::block_on::h3f2ef3f11fb19ca1
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/mod.rs:441
  44:     0x55b91d02c378 - tokio::task::local::LocalSet::block_on::h4d8ae566fc6f16e6
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/task/local.rs:353
  45:     0x55b91d04f81f - actix_rt::runtime::Runtime::block_on::hcb24704697ad2642
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.1/src/runtime.rs:89
  46:     0x55b91cfc8b7b - actix_rt::builder::SystemRunner::block_on::he5aedab5b47cf63a
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.1/src/builder.rs:187
  47:     0x55b91d044ec2 - test_runner::main::h017443cc26041b8c
                               at src/main.rs:64
  48:     0x55b91d03e2bb - std::rt::lang_start::{{closure}}::h5fdd8b9faa19c9fc
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/rt.rs:67
  49:     0x55b91d89f753 - std::rt::lang_start_internal::{{closure}}::h5d3ea623498f5f43
                               at src/libstd/rt.rs:52
  50:     0x55b91d89f753 - std::panicking::try::do_call::hac65e71be769a440
                               at src/libstd/panicking.rs:348
  51:     0x55b91d89f753 - std::panicking::try::hd4706e264bcf6712
                               at src/libstd/panicking.rs:325
  52:     0x55b91d89f753 - std::panic::catch_unwind::h948a0fb4a8b3ee82
                               at src/libstd/panic.rs:394
  53:     0x55b91d89f753 - std::rt::lang_start_internal::h72cc068ed2d0ac53
                               at src/libstd/rt.rs:51
  54:     0x55b91d03e297 - std::rt::lang_start::h31d39fb8af367732
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/rt.rs:67
  55:     0x55b91d044f2a - main
  56:     0x7f50da1a1042 - __libc_start_main
  57:     0x55b91cfc822e - _start
  58:                0x0 - <unknown>
Panic in Arbiter thread.
```
The block field is `null` so the tests are failing - any ideas?

**Comment by shravanshetty1** [comment]
> Thanks for reporting!
> From the error message I assume `npm run typechain` in `/solidity` was not executed.

Also i think it should be explicity mentioned in the readme that `typechain` needs to be generated before tests are run

**Comment by shravanshetty1** [comment]
CI/CD for integration tests seem to be not running any tests
![Screenshot from 2020-09-18 09-27-17](https://user-images.githubusercontent.com/58299697/93554896-2fc1e880-f992-11ea-8b0a-6fbab468bd7a.png)
In the CI/CD file its using the `cargo test` command while in `integration_test.sh` in container scripts its using `cargo run`

**Comment by alpe** [comment]
Caused: https://github.com/althea-net/peggy/pull/22

**Comment by jkilpatr** [comment]
Hey @shravanshetty1  we have CI running a full validator set update as of about a week ago.
