### ISSUE TITLE
Non unique Nonces on the cosmos side

### ISSUE THREAD

**Issue by alpe** [althea-net/peggy#41]
We use the block height for nonces in the multisig update at the moment. 
But the block height is reseted when the cosmos chain is restarted after an upgrade.

**Comment by jkilpatr** [comment]
this will have to be persisted in  #64  and reloaded. So the counter, when there is no existing value takes the block height, otherwise it takes the genesis last highest nonce + the current block height. That should work ok.

**Comment by alpe** [comment]
`genesis last highest nonce + the current block height` is a more complex solution than an incrementing counter. It would save some gas as there is no "store" on the cosmos side but it would **require a human to set this counter manually after a state dump with the current value from Ethereum**. From my experience this is very error-prone and not very common in the cosmos world.
What is the benefit of using the current block height?

**Comment by jtremback** [comment]
Not really following what the difference between these two solutions is, but I would agree that the block height will end up being unreliable after an upgrade. Seems best to keep an incrementing counter instead.

**Comment by jkilpatr** [comment]
@alpe  on further consideration there's no benefit just keeping a counter around in storage is the correct solution.

**Comment by jtremback** [comment]
resolved by https://github.com/althea-net/peggy/pull/92
