### ISSUE TITLE
Support Cosmos bech32 Address for the bridge contract destination

### ISSUE THREAD

**Issue by alpe** [althea-net/peggy#46]
I would expect a user to copy paste his address into his preferred wallet application. Therefore the bech32 representation makes most sense for me to have a good UX.

Currently a `byte32` type is used. 
The cosmos byte representation is 20 bytes  but bech32 would be longer:
A cosmos hub address example: `cosmos1just6dugs6u7080rcqyrq9g6yr38gl9fl3j4ul`.
See other [`bech32 addresses`](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki#test-vectors)

**Comment by jkilpatr** [comment]
Bridge contract is not supposed to be user friendly. We're going for maximum security and it's the job of the client utilities (which we're also writing) to make things easy to use.
