### ISSUE TITLE
TransferOutEvent should contain sender address

### ISSUE THREAD

**Issue by alpe** [althea-net/peggy#47]
I was assuming that we want to fully document the deposit also on the [cosmos side](https://github.com/althea-net/peggy/blob/master/module/x/peggy/types/msgs.go#L437).  This assumption may be wrong so we better discuss this early.

Without the sender address in the `TransferOutEvent` there is some additional complexity on the orchestrator (any client) to collect data from this and the ERC20 event that we should avoid.

Currently we do `emit TransferOutEvent(_destination, _amount)`.

**Comment by alpe** [comment]
We would also need:
* ERC20 contract address
* ERC20 human readable symbol

to uniquely identify a token on the cosmos side and to provide the data for clients

**Comment by jkilpatr** [comment]
@alpe  I think this is included in the message right now?

**Comment by alpe** [comment]
ja, the [message](https://github.com/althea-net/peggy/blob/master/module/x/peggy/types/msgs.go#L344-L349) is prepared to include the data already.
The logic on the cosmos side requires it to store the `BridgedDenominator` data and mint voucher tokens.

I was assuming we will have 
```
event TransferOutEvent(uint256 _nonce, address _erc20ContractAddress, string _symbol, string _destination, uint256 _amount);
``` 
as in my [demo]( https://github.com/althea-net/peggy/pull/56/files#diff-1403e22b33b0894c8c44d663ed265373R479)

**Comment by jtremback** [comment]
I agree with this

**Comment by alpe** [comment]
There is more data we should expose via event:
- sender's Ethereum address (to support a process for invalid cosmos addresses)
- token decimal (which is defined in erc20 contracts as I learned to be used as metadata for any UI)

**Comment by jkilpatr** [comment]
token decimal is a good point I'll add it.
