### ISSUE TITLE
Define `nonce` for Bridge contract deposit

### ISSUE THREAD

**Issue by alpe** [althea-net/peggy#48]
To prevent duplication of deposits on the cosmos side we need an unique identifier (nonce).
This nonce will likely be used by the orchestrator to skip previously submitted events.

With a combination of big endian encoded `BlockNumber` and `Index` we can support both use cases. For the cosmos side no semantic is needed though. The orchestrator could query the last nonce and extract the payload. No local state would be needed.

Fields available from an event:

```
	// Derived fields. These fields are filled in by the node
	// but not secured by consensus.
	// block in which the transaction was included
	BlockNumber uint64 `json:"blockNumber"`
	// hash of the transaction
	TxHash common.Hash `json:"transactionHash" gencodec:"required"`
	// index of the transaction in the block
	TxIndex uint `json:"transactionIndex"`
	// hash of the block in which the transaction was included
	BlockHash common.Hash `json:"blockHash"`
	// index of the log in the block
	Index uint `json:"logIndex"`
```

**Comment by alpe** [comment]
I have changed my mind:
The relayer should not make assumptions about the nonce but let the contract return one instead. We should modify the contract and return a nonce and additional payload data for the cosmos side:
```    
event TransferOutEvent(uint256 _nonce, address _erc20ContractAddress, string _symbol, string _destination, uint256 _amount);
```

**Comment by jkilpatr** [comment]
Nonces imply a strict ordering of operations, deposits have no strict ordering. Therefore a nonce doesn't make sense as a unique identifier. It should have a hash if we need a unique identifier and I don't see why we need the contract to define one, we can simply use the Ethereum txhash or some other existing unique value.

**Comment by jkilpatr** [comment]
I'm switching the assignment of this issue to you, please add a nonce field (64 char hex string) to the deposit message and then I can hook up the orchestrator to submit the ethereum txid in that slot.

I tried to make this change myself but I don't really grok the way it works with your oracle event interface.

**Comment by alpe** [comment]
I am not very familiar with Ethereum but in my understanding state machines imply a deterministic processing and therefore a strict order of operations. I don't think there can be 2 deposits at the same time so there is an order and the contract would be able to use a counter as a nonce for it. This order should also be reflected in the event system.
Nevertheless I can add an "Ethereum TX id" to the persistence store but we would have to store all TX ids for ever to not allow  duplicates. An incrementing nonce would be a much simpler solution for an "ordered" channel.

**Comment by jtremback** [comment]
I'm not sure right now, but do you even get an Ethereum txid from an event @jkilpatr ? If not, then @alpe is right that we need some kind of unique ID for them. All the current fields in the sendToCosmos event could be the same between two different txs. 

If the unique ID is being created by the contract logic, then an incrementing nonce would be the easiest way. I'd like to avoid the storage write, but I can't think of an easier way right now.

**Comment by jtremback** [comment]
If the model is that everyone comes to consensus on the events that are in a block, and there are no errors in the Ethereum client that is giving everyone the events, then you could do without the nonce. This is probably the case. One could argue that if we have Eth clients all duplicating events, there are big problems afoot with Ethereum. If we're going to assume arbitrary inaccuracy, they could just as easily be losing events, which is something we can't do anything about.

On the other hand the nonce is a small change, and definitely doesn't hurt security.

The question is: do we want every user of Peggy to pay an additional small gas cost to guard against a failure that may not even be possible?

I would say that if we can prove to ourselves that duplicated events from Ethereum are not possible, at least not without a failure of Ethereum itself, then I think we can forget the nonce. If not, then we should use it.

**Comment by jtremback** [comment]
> Nevertheless I can add an "Ethereum TX id" to the persistence store but we would have to store all TX ids for ever to not allow duplicates.

There's a big question here and that is: Is it possible for us to get duplicate events from an Eth client if Ethereum is working correctly?

I agree that storing every txid ever could be untenable, but adding a nonce will add a small additional Ethereum gas cost for every user of Peggy, forever. 

If there is a risk of duplicate events, then it would be worth it, but we should be sure of that. It may be that duplicate events cannot happen on Ethereum without there being something very wrong with Ethereum. If we're going to be guarding against arbitrary failures of Ethereum, why aren't we guarding against missing events? Or events that never existed in the first place?

Other possible solutions:

- Store a rolling history of txids. Maybe we think that duplicates are possible close together, but that it's less likely that we'll get duplicates of an event from long ago.

- Bloom filter. Probably overenineering.

**Comment by jtremback** [comment]
@alpe We are going to go with your nonce design. I will add it to the contract and event.

**Comment by jkilpatr** [comment]
@alpe After discussing with @jtremback  we both agree that one piece of temporary storage on Ethereum is superior to storing an ever growing amount of Ethereum transaction IDs on Cosmos just to use as unique identifiers. Especially since we would need to iterate over this list before allowing any new deposit transaction into the chain.

You're design is by far the more correct one here.

**Comment by jtremback** [comment]
I think that it's likely that this nonce is not actually required, and we could get all the assurances in other ways, but it's much simpler this way and we control every part of the security this way.

**Comment by jtremback** [comment]
What should we do in the cosmos module when we detect a duplicate nonce? Is it enough to just reject the tx, or do we have to halt the chain or raise the alarm or something?

**Comment by jkilpatr** [comment]
I think it's sufficient to reject it, it's simply invalid isn't it?

**Comment by alpe** [comment]
With an ordered channel we can have a simple logic where we 
* reject nonces < last observed 
* accept nonce = last observed +1 when attestation process was not started or attestation process started and timeout has not happened, yet
* reject nonce = last observed +1 when attestation process was completed
* reject nonce > last observed +1 

We should plan for the unhappy path where an attestation times out. This would probably result into slashing the proposer and supporters in the normal case. But it might not be a malicious intend but a global network issue. Definitively off topic for this issue.

**Comment by jkilpatr** [comment]
this is in progress code wise in #92
