### ISSUE TITLE
Flesh out the bootstrapping process

### ISSUE THREAD

**Issue by jkilpatr** [althea-net/peggy#5]
The bootstrapping process for starting a new bridge needs to be finalized. 

This includes issue #12 as part of the problem.

Followed with the issue of how to select the correct bridge in a decentralized manner

**Comment by jtremback** [comment]
This is in notes.md but needs polish and is out of date.

**Comment by jkilpatr** [comment]
#25 addressed some of this, need to determine if this issue can be closed or if more work is needed.
