### ISSUE TITLE
ValsetUpdatedEvent should contain nonce and newCheckpoint

### ISSUE THREAD

**Issue by alpe** [althea-net/peggy#53]
With `nonce` and the `newCheckpoint` we can validate on the cosmos side that the update was successful. The orchestrator would not need to preserve state.
Currently we do: `emit ValsetUpdatedEvent(_newValidators, _newPowers);`

**Comment by alpe** [comment]
The checkpoint is not necessary to be exposed via event if it is available from the contract by a query for example.

**Comment by jkilpatr** [comment]
it's available from a contract query. I added a nonce this weekend, resolving.
