### ISSUE TITLE
Conflict with withdrawal TX nonces ASC and by fee DESC order

### ISSUE THREAD

**Issue by alpe** [althea-net/peggy#61]
The unique ID that is used for transactions on the cosmos side is based on an incrementing counter but collecting TX and ordering for batches is based on `fees` with desc value. 
The problem I see with the current bridge contract [implementation](https://github.com/althea-net/peggy/blob/master/solidity/contracts/Peggy.sol#L286) is that we can not use the unique TX ID as nonce and enforce incremental order while also building batches with TX ordered by fee.

For example:

|TX| ID| amount| fee|
|---|--|---|-|
| A | 1 | 1 T | 1 T |
| B | 2 | 1 T | 3 T|  
| C | 3 | 1 T | 2 T|

If we order by fee, we would have `B,C,A` by ID `A,B,C`

I would propose to drop the TX nonces in the contract method in favour of a single check for batch nonce > previous so that we do prevent double spending due to resubmission.
We would also need the batch nonce emitted as event for the cosmos side to update state

**Comment by jkilpatr** [comment]
IMO transactions are only given a nonce when included in a batch. We use some other identifier for when the transactions are in the mempool.

**Comment by alpe** [comment]
> IMO transactions are only given a nonce

The identifier (ID) of a transaction should not change during its whole lifetime so that we can track all operations and prevent double spending. Adding a TX to a batch therefore should not change it either so that we ensure it is assigned only once. As the unique and incrementing `nonce` for the bridge contract the ID does not fit.

We could use `batch_id * max_batch_items + tx_pos_in_the_batch` but this won't be any better than just checking for the `batch_id > last_batch_id` IMHO.

**Comment by jtremback** [comment]
Let's take another look at what the tx nonces were intended to accomplish and see if we can solve this. I think we have kind of a backlog of thinking around nonces and the tx batch concept that needs to be implemented or at least documented. I would be open to having a call about this some time. @jkilpatr @alpe

**Comment by jtremback** [comment]
Thanks for noticing this. We are now switching to a per-batch nonce.
