### ISSUE TITLE
Store current validator set state

### ISSUE THREAD

**Issue by jkilpatr** [althea-net/peggy#62]
We should store the complete Ethereum contract validator state in the Cosmos module store.

Without it it's difficult to determine exactly what signatures we need to complete operations.

This list would be used to determine when batches and validator set update operations have enough signatures and would be updated when the oracle transactions for those operations pass the threshold.

**Comment by alpe** [comment]
We have this data already:
1. Bootstrap: data is imported into cosmos side via orchestrator
2. Multisig update: data is originated from the cosmos side. Bridge contract exposes an event which is propagated to the cosmos side via orchestrator. An Index points to new Multisig data set.

The problem are the "in flight" updates. We can not tell when an update is executed until the event was observed. During this time we may operate with an outdate MultiSig set.
To address this we can be
A) Optimistic where we always send the last valset that has enough signatures and may pass
B) Pessimistic where we stop any operations with the bridge until we have the new multisig update observed

Option B feels simpler for MVP. There is some complexity to report errors in A and cancel the operations on the cosmos side...

**Comment by jkilpatr** [comment]
I think I'm in agreement with B I actually think that's viable even for a production bridge.

**Comment by jkilpatr** [comment]
I've discussed this issue with @jtremback  and we've decided a few things that we're going to go over on tomorrows call

First and foremost we shouldn't actually be depending on knowing the validator state on the Ethereum side in any way.

We don't need to do A OR B because that's not a thing the validators care about. It's the job of the relayers to carry valsets over and perform updates. The validators themselves just make validator sets upon request. This works because everything to do with the contract has been carefully designed to be eventually consistent and eventually correct, anything demanding more closely tied operations is asking for race conditions because you simply can't closely coordinate operations in that way.

**Comment by jkilpatr** [comment]
Obviously you do have to take action when an oracle event is submitted (for example that a tx batch has passed) but in any case the bridge is in a valid state. 

Lets say we have no oracle operations for a week. Totally isolated form Ethereum (except we assume one way validator set updates from cosmos -> eth we have no knowledge that they have been submitted on the Cosmos side).

So Cosmos chain keeps getting valset update requests and producing updates, likewise it keeps on making transaction batches. At the end of the week oracle operations start coming through. No matter how the outstanding operations have played back there is some correct ordering of payments either making it across or going back into the pool after being in limbo for a week. Timing or even knowing exactly what is on the other side when making a batch or validator set update isn't relevant.

As long as a validator set is produced any time there is a handoff of more than 33% voting power it is possible to play back arbitrary chains of validator sets just fine. 

And as long as tokens are held until a batch has an oracle event we can guarantee that a batch either gets sent or refunds users, we just can't guarantee how long it will take.

**Comment by jkilpatr** [comment]
I think this issue has become a duplicate of #70  I'm going to close it, please reopen with reasoning if there's something unaddressed here that's not being addressed there.
