### ISSUE TITLE
Struct instead of parallel arrays for validator state

### ISSUE THREAD

**Issue by jkilpatr** [althea-net/peggy#63]
Having parallel arrays flying around everywhere is just asking for trouble. This should be resolved before we get much further into implementation.

**Comment by jtremback** [comment]
Is this an issue on the Cosmos code or the solidity? As we've discussed before, AFAIK the functionality of passing an array of structs into a contract still requires a compiler flag for some kind of experimental ABI parser. It hasn't seemed worth using an "experimental" flag on the contract just to get a cleaner API.

I would agree though, it should be structs everywhere and then be turned to parallel arrays right before calling the contract.

**Comment by alpe** [comment]
This was about the cosmos endpoints
