### ISSUE TITLE
Everywhere Peggy lists a validator set should be sorted by power

### ISSUE THREAD

**Issue by jkilpatr** [althea-net/peggy#65]
This is a particular problem for signatures as everyone needs to have the same validator set order at all times.

To that end we should sort the validator set by power at every opportunity and everywhere it is displayed to an external application.

By providing consistent ordering external application can not concern themselves with sorting and simply sign or verify signature with the validators in the order they are provided. 

This depends on #63 and must happen after that's merged.

**Comment by jtremback** [comment]
The contract does not check if the valset is properly sorted, so it is entirely possible for the validators to shoot themselves in the foot and submit an unsorted valset

**Comment by alpe** [comment]
This was implemented on the cosmos side.
