### ISSUE TITLE
Clarification on whether or not validators need to have knowledge of the current valset

### ISSUE THREAD

**Issue by jtremback** [althea-net/peggy#70]
There has been some confusion about whether validators need to have knowledge of the old valset to be able to produce a new valset. I'm writing this issue to clarify that with the current code, they do not. It's an easy misunderstanding to have since the Solidity code is unfortunately somewhat obfuscated due to the gas optimizations and compiler limitations it was written under.

Anyway, I will demonstrate here that in no case must the validators have knowledge of the current valset to produce a new one. The only requirement is that they choose a nonce which is higher than the nonce of the current valset. First, i'll briefly explore where this misunderstanding likely came from:

```sol
	function updateValsetAndSubmitBatch(
		// The validators that approve the batch and new valset
		address[] memory _currentValidators,
		uint256[] memory _currentPowers,
		uint256 _currentValsetNonce,
...
```

All of the cosmos-facing methods in `Peggy.sol` include the current valset as arguments. This is due to the gas optimization we are using where we store only a hash of the valset (the checkpoint) rather than the entire data. But this is functionally equivalent to actually storing the data. The important part is that the only person who needs to know about the current valset is the person who submits the Ethereum transaction. This is not necessarily a validator, and it is not the validator set as a whole. It could be anyone. This person can easily tell what the current valset is because they are not constrained by the **n** block delay that the validators have in coming to consensus on the state of the Ethereum blockchain.

Let's look at what the validators actually do need to know about the state of the Ethereum blockchain to successfully sign a valset.

```sol
		// Check that the valset nonce is greater than the old one
		require(
			_newValsetNonce > _currentValsetNonce,
			"New valset nonce must be greater than the current nonce"
		);
```

First there is a requirement that valset nonces are strictly increasing. But this does not mean that the validators must know what the current nonce is. They can achieve this simply by incrementing the nonce with every valset they sign.

```sol
		// Check that the supplied current validator set matches the saved checkpoint
		require(
			makeCheckpoint(
				_currentValidators,
				_currentPowers,
				_currentValsetNonce,
				state_peggyId
			) == state_lastCheckpoint,
			"Supplied current validators and powers do not match checkpoint."
		);
```
Above, for clarity, is where the current valset actually gets used. It is checked against the stored checkpoint. This is an alternative to storing the current valset in the contract's memory, which costs about 4x as much gas. However, if these lines of code simply loaded the current valset from the contract's memory, then the caller would not have to pass it in at all and the rest of the logic would be unchanged. Again, this does not involve the validators knowing about the current Ethereum state.

```sol
		bytes32 newCheckpoint = makeCheckpoint(
			_newValidators,
			_newPowers,
			_newValsetNonce,
			state_peggyId
		);

		// Check that enough current validators have signed off on the transaction batch and valset
		checkValidatorSignatures(
			_currentValidators,
			_currentPowers,
			_v,
			_r,
			_s,
			// Get hash of the transaction batch and checkpoint
			keccak256(
				abi.encode(
					state_peggyId,
					// bytes32 encoding of "valsetAndTransactionBatch"
					0x76616c736574416e645472616e73616374696f6e426174636800000000000000,
					_amounts,
					_destinations,
					_fees,
					_nonces,
					newCheckpoint
				)
			),
			state_powerThreshold
		);
```
Here is where we can see what the validators actually do sign over and thus need to know about. The current validators signatures are checked over 2 main things: the transaction batch, and the newCheckpoint, which is digest of the new valset. Nowhere must the validators sign over the current valset. Some knowledge of the Ethereum state is required to make a transaction batch, but this is nuanced and out of the scope of this issue.

The signatures of the current valset are required. But not necessarily the whole valset. If a valset that is less than 1/3 different than the contract's recorded current valset signs, it will still work, since the method that checks the signatures only requires 2/3's of the current validation power be present.

**Comment by jtremback** [comment]
@alpe Does this address the concerns you raised in Monday's standup or is there still something I'm not understanding?

**Comment by alpe** [comment]
@jtremback thank you very much for the detailed explanation. It makes sense for the contract but I see the problem on the orchestrator and cosmos side.

> ... the only person who needs to know about the current valset is the person who submits the Ethereum transaction. This is not necessarily a validator, and it is not the validator set as a whole. It could be anyone.

This is correct. Orchestrators would have to keep state of what the "last" successful update was and submit that data with the next update to the Ethereum side. (Optimistic approach) 
* How does the cosmos side know that >2/3 of the orchestrators (in the multisig) have signed the next valset update? The last known data is stale with any inflight update
* What happens in case of a fork within the 50 block delay in the orchestrators?

This goes back to the decision if we either implement an optimistic or pessimistic approach. Either or we should build this approach into the cosmos side. IMHO the orchestrator should not have complex state or logic.

For both approaches we would need an additional message where the orchestrator informs the cosmos side about a submission to the Ethereum side (which is not an oracle message). And a message to notify about an submission failure (or fork) to revert that state.
In case of a pessimistic approach we can allow only 1 inflight multisig update (within 50 blocks window). With an optimistic approach the "last submitted" multisig set can be used for the 2/3 signature tally.

**Comment by jtremback** [comment]
There's a terminology issue here that confuses matters IMO. The "orchestrator" is a codebase which performs two completely separate functions- that of an "eth signer", and that of a "relayer". I'm going to refer to "eth signers" and "relayers" here, regardless of whether or not it is convenient to put both sets of functionality in a single binary from an implementation perspective. I didn't want to argue too much with the "orchestrator" term because it seemed like bikeshedding but at this point it is making things hard to discuss.

Anyway, the "eth signer" is a binary run by every validator. It signs stuff using an Ethereum key, since for various reasons, we did not want to build this functionality into the cosmos module. It also passes information from Ethereum into the cosmos module state. I won't discuss this much further since it exists mostly as a artifact of code organization.

The "relayer" submits Ethereum transactions on behalf of the validator set. It is supposed to do this purely to collect fees, but in some cases our design will still require altruistically motivated relayers (in the case of a valset update without a batch). But that detail isn't important here.

> This is correct. Orchestrators would have to keep state of what the "last" successful update was and submit that data with the next update to the Ethereum side. (Optimistic approach)

I'm assuming that what you're talking about here is the relayer getting the current valset whose signatures will be checked by the contract. The relayer can simply look at the most recent `ValsetUpdatedEvent` from their chosen Ethereum node. It does not need to be delayed by 50 blocks since it is not come to consensus on. No state needs to be maintained by our code for this.

> How does the cosmos side know that >2/3 of the orchestrators (in the multisig) have signed the next valset update/ batch? The last known data is stale with any inflight update

If you're asking how the cosmos side prepares a valset update, I think this is a matter for the cosmos side which does not involve the contract, or a knowledge of the Ethereum state at all. The only way that the cosmos validators would need to know about the current Ethereum state is to know *which validators should sign the update*. But we will just have the entire validator set sign the update each time. We can view the eth signer as a part of the consensus process so this will happen as long as the chain is running. 

There could be an issue if the validator set changes by more than 1/3 between the signing of two valsets. This is a failure mode which we should examine carefully, but it involves some pretty big events on the cosmos side.

> For both approaches we would need an additional message where the orchestrator informs the cosmos side about a submission to the Ethereum side (which is not an oracle message). And a message to notify about an submission failure (or fork) to revert that state.

> In case of a pessimistic approach we can allow only 1 inflight multisig update (within 50 blocks window). With an optimistic approach the "last submitted" multisig set can be used for the 2/3 signature tally.

Can you define the failures that occur without this additional message? I think it would help me understand.

**Comment by jtremback** [comment]
Hey, just talked about this with @jkilpatr and looked back through the docs and I think that i see the error in our documentation and possibly thinking. 

In overview.md we have these paragraphs:

- Confirmed - Many actions in Peggy require RLP encoded signatures to be submitted by the Orchestrators, an operation is Confirmed when it is possible to execute it on Ethereum by collecting and submitting these RLP encoded signatures representing 66% of all voting power encoded in the Last Valset.

- Observed - events on Ethereum are considered Observed when 66% of the active Cosmos validator set during a given block has submitted an oracle message attesting to seeing the event. Note this is distinct from Confirmed! At any given time the set of who can Observe an event and who can Confirm and event will be slightly different. Since Confirmed is based off of the Last ValSet and Observed is always up to date with the latest validator set.

Looking closely at:

> an operation is Confirmed when it is possible to execute it on Ethereum by collecting and submitting these RLP encoded signatures representing 66% of all voting power encoded in the Last Valset.

This implies that the validators would have knowledge of what the Last Valset is. It's possible to eliminate this requirement by considering an operation Confirmed when there is only one signature on it, because maybe that one signature was 2/3's of the last valset power. It may actually be best to eliminate the concept of Confirmed entirely.

**Comment by alpe** [comment]
> Can you define the failures that occur without this additional message? 

Without a "submitted to Ethereum" message the cosmos side has no information about an inflight multisig update. This means for the "optimistic" approach it must assume any multisig update that reached the signature threshold before the timeout is submitted successfully and therefore the "current" multisig. The "current" multisig would be used to authorize new signature submissions from orchestrators. Worst case would be lock out from Ethereum multisig due to lazy or failed submissions.
For a "pessimistic" approach we must also assume the update was submitted and block any new multsig update "requests" until the event was "observed". This affects throughput.



> It may actually be best to eliminate the concept of Confirmed entirely.

We could move the logic into the orchestrator but this is a design decision. I personally prefer light clients so that people can replace them in their favourite language and toolset but that is me.
I understand "eliminating" as not doing a tally or waiting for a threshold. Technically that can work but likely just burns gas until the threshold is reached. I guess that is not what you had in mind. Can you please elaborate with an example how the process can work?

> This implies that the validators would have knowledge of what the Last Valset is.

Without this knowledge the cosmos side must accept any signature submission that comes from a validator as it can not identify if it is in the "current" multisig set. This would reduce the cosmos side mostly to a distributed store when collecting signatures. We can not do a tally or sort by power on an endpoint as that data would not be available. This can be a design decision.
It would be good to understand the workflows better from your perspective. A process spec with the orchestrator would be very helpful.

**Comment by jtremback** [comment]
I'll write my understanding of the relevant parts here first, we can add it to the docs later. This is somewhat different than is in overview.md right now, we will have to revise it once we have figured this all out.

1. Users send txs requesting to send some tokens over to Eth
   1. The tokens on the cosmos side are no longer transferable at this point
   1. These txs go in a pool
1. Someone requests a batch
1. A batch is assembled which contains the most profitable txs possible, and goes into the batch pool
   1. The batch has a nonce which is always incremented
   1. The batch includes the latest valset
   1. The txs in this batch are removed from the tx pool
1. Batches in the batch pool are signed over by the validator's eth signers
   1. Once a batch has enough signatures, a relayer can submit it to Eth (note that the determination of whether or not it has enough signatures is left completely to the relayer)
1. Once a batch has been observed to have been submitted to Eth, any batches in the batch pool with a lower nonce, which have not also been successfully submitted, have their txs released back into the tx pool to be tried in a new batch

**Comment by jtremback** [comment]
> The "current" multisig would be used to authorize new signature submissions from orchestrators.

Not sure I follow. Anybody can sign over any batch+valset they want. A relayer can submit one of these when it sees that it has enough signatures to be accepted by the contract.

> I understand "eliminating" as not doing a tally or waiting for a threshold. Technically that can work but likely just burns gas until the threshold is reached. I guess that is not what you had in mind. Can you please elaborate with an example how the process can work?

We really need to separate the concepts of relayer and eth signer here, even though they are both being implemented in a single Rust program which we are calling the "orchestrator".

Relayers are free to burn gas by submitting batches without enough signatures if they want. It's not a security concern, and it's not a concern of the validators. A relayer can avoid this wasted gas by checking what Peggy.sol's valset is right before they submit the update. No 50 block delay is required because there is no consensus involved, just a decision by a single relayer.

**Comment by alpe** [comment]
Thanks for the additional information. I do understand better now what you had in mind. I have added some new issues to track work based on your comments. Some of the logic that is in the cosmos side will need to move to the orchestrator. 
#82 addresses the tally process and state to be removed from the cosmos side

**Comment by jkilpatr** [comment]
@alpe  @jtremback  I think we can close this issue now? Or are there further action items (like making this clearer in repository documentation?)
