### ISSUE TITLE
If Cosmos denom includes information other than the token contract address, it is a security issue

### ISSUE THREAD

**Issue by jkilpatr** [althea-net/peggy#76]
Right now we have

`Peggy<ShortHash>`

I think we should have `<4 char denom><ShortHash>P` 

where the trailing P indicates that this is a Peggy token, the short hash is the same hash of the token contract address and the denom is human readable. This provides the same level of hash security as the current naming scheme (the short hash remains the same length since peggy is 5 chars and we use 4 for the denom at most and one for the trailing P) but is much more human friendly.

We should also implement a hash collision detector and handler, but that's another issue.

**Comment by jkilpatr** [comment]
See my incomplete pull request 7d86372 from #77 which isn't mergeable now and I need to go cherry pick what I want to keep. Got lost in the brokenet shuffle.

**Comment by alpe** [comment]
Please see my comment on https://github.com/althea-net/peggy/pull/77#discussion_r511766972

IMHO it would be best to get some input from wallet developers how they integrate IBC and what would be best for Peggy

**Comment by jkilpatr** [comment]
@alpe  you're correct ultimately this is just a wishlist issue that would make non-production testnets nicer to use for the short time before we rebase onto Stargate. I will mark it as low priority.

**Comment by jtremback** [comment]
I have a related comment:

Any reduction of the address length is a reduction in security. I understand that Stargate will remove the 15 character limit. At this point, we should include the whole token contract address. 

I tend to agree with @alpe that including the token symbol is of questionable usefulness. We should just make it easy to parse the address out of the Cosmos token naming scheme.

I don't understand the point of hashing the address. It does nothing useful cryptographically, and just destroys information.

**Comment by jtremback** [comment]
Also, I don't think there's anything stopping any ERC20 contract from changing its symbol. This could really mess things up. Think about this scenario:

- An ERC20 token returns "MAX" when you check its symbol. The Eth Signer reports some deposits of this token back to the Peggy module. The Peggy module creates tokens on the Cosmos side with a symbol that includes MAX.
- The ERC20 changes its symbol. Now a new token is created on the Cosmos side.

I can't think of an attack right now that utilizes this, but I'm sure someone could. @jkilpatr at this point I am strongly recommending that we remove the symbol from the Cosmos token identifier.

**Comment by jkilpatr** [comment]
:+1:  just contract address is sufficient. I think we can just open a pull request to remove the symbol.

**Comment by jkilpatr** [comment]
this is resolved in #115
