### ISSUE TITLE
Discuss 'Orchestrator' naming

### ISSUE THREAD

**Issue by jkilpatr** [althea-net/peggy#83]
@jtremback  has brought up that 'orchestrator' is a little too vague. It's really just a peggy relayer combined with an Ethereum signer and Oracle module. 

We could just call it 'Ethereum signer'

**Comment by jtremback** [comment]
It's an "Eth Signer" plus a "Relayer". My main quibble with it is not so much the word as the fact that it combined two very different roles.

**Comment by jkilpatr** [comment]
well yes a lot of things going into the same binary. In fact it looks like Peggy is going to have 4 binaries coming out of the same crate with overlapping roles.

One that's run in tests
One that registers ethereum keys (and later submits a proxy comsos address for the validator)
One that just relays Cosmos -> Ethereum
One that is a combined relayer and oracle
