### ISSUE TITLE
Outgoing TX batch includes latest valset

### ISSUE THREAD

**Issue by alpe** [althea-net/peggy#84]
See https://github.com/althea-net/peggy/issues/70#issuecomment-715626034

- [ ] Cosmos
- [ ] Orchestrator
- [ ] Ethereum contract

Work on Cosmos side was started in https://github.com/althea-net/peggy/pull/75

**Comment by jkilpatr** [comment]
I think this is good to close @alpe  @jtremback  fixed your review on #75 but I merged it before you could update your review. My apologies on that.
