### ISSUE TITLE
Possible sybil attack vector

### ISSUE THREAD

**Issue by jtremback** [althea-net/peggy#89]
In https://github.com/althea-net/peggy/blob/master/module/x/peggy/types/attestation.go#L253 is the following code:

```Go
// ThresholdsReached returns true when votes power > 66% of the validators AND total votes > 50% of the validator count
func (t AttestationTally) ThresholdsReached() bool {
	return t.TotalVotesPower.GT(t.RequiredVotesPower) &&
		t.TotalVotesCount > t.RequiredVotesCount
}
```

Why look at the number of votes? This is a sybil attack vector.

**Comment by jkilpatr** [comment]
Lets explain the reasoning here, if you make a large number of low power validators, and then have those validators refuse to vote they could halt withdraws despite only using a very small amount of total stake.

Of course this is only possible on a chain with validator slots open but it's still a valid attack. Did you have a different vulnerability in mind when you added this @alpe ?

**Comment by jtremback** [comment]
Just to put this in perspective, the bottom 50% validators on the hub as of this July (this is just what i happen to have on hand) had a power of 755 vs the top validator's power of 707 (these numbers are normalized to 10000). So two or three of the top validators would be able to freeze the bridge with a sybil attack.

In that case, 7.5% of the power would be able to freeze the bridge instead of the intended 33%

**Comment by alpe** [comment]
@jtremback thanks for the good explanation! This is "legacy" code that I had proposed in some other context/issue but in the discussion the consent was already that it should be removed. 
It was not on the critical path for MVP that is the only reason it is still here. I will keep this issue as a reminder and address this soon.
Feedback on the code is very much appreciated. 💐

**Comment by jkilpatr** [comment]
@jtremback  did you patch this in #92 ?

**Comment by jtremback** [comment]
@jkilpatr Yes, we are now using an array of validators who get summed each time, so this is no longer the same code
