### ISSUE TITLE
Contract upgradability

### ISSUE THREAD

**Issue by jtremback** [althea-net/peggy#93]
In discussing whether a feature should be implemented cheaply on Ethereum or more expensively on Cosmos today, I found myself wishing that we had a way to upgrade the Peggy contract after it is deployed.

A proxy contract pattern would allow us to do this, at the cost of extra code complexity.

Briefly, the public facing Peggy contract would call into another contract which could be changed after deployment. The validators could create a special transaction changing the contract. The benefit of this is that Peggy's address on Ethereum would not change after an upgrade.

This would not affect the security model at all, since the validators with the power to upgrade the contract would also have the power to just steal the funds anyway. It would add some complexity to the code.

**Comment by taariq** [comment]
I like the opportunity leverage proxy contracts for upgrades. This is very
helpful.

**Comment by jtremback** [comment]
@taariq Yea, our conversation the other day might have been in the back of my mind!

**Comment by alpe** [comment]
It would be a big risk to not prepare an upgrade path IMHO. I can not comment on the proposed solution but I am happy that this discussions happens now. 🌻

**Comment by jtremback** [comment]
@alpe On a smart contract chain like Ethereum, there is no obvious way to have a trustless contract upgrade, since there is no chain governance, and if there was, it wouldn't be concerned with upgrading someone's random contract.

People used to use a proxy pattern like i described with a dev holding the backdoor key. But then it was realized that this is a very bad idea and completely trustful, and the dev could run away with the funds as well as putting themselves at legal risk just for having the backdoor.

So most major Ethereum contracts like Uniswap or Dai are simply not upgradable. They just have to make sure that the contract is correct before deploying. When these are upgraded, it is a new contract with a new address.

With Peggy, we have the ability to do trustless upgrades since the validator set as a whole can hold the upgrade backdoor. This is pretty new and unique to Ethereum though. 

Just giving all that background to say that I don't think upgradability is essential, but it does seem like a very useful feature.

**Comment by jtremback** [comment]
Closing this for now
