### ISSUE TITLE
Full bootstrapping process

### ISSUE THREAD

**Issue by jtremback** [althea-net/peggy#94]
I'm going to paste the specification from overview.md and we can discuss it.

## Bootstrapping

We assume the act of upgrading the Cosmos-based binary to have peggy module is already complete,
as approaches to that are discussed in many other places. Here we focus on the _activation_ step.

1. Each `Operator` generates an Ethereum and Cosmos private key for their `EthSigner`. These addresses are signed and submitted by the Operators valoper key in a MsgRegisterEthSigner. The `EthSigner` is now free to use these delegated keys for all Peggy messages.
1. A governance vote is held on bridge parameters including `Peggy ID`, `Allowed validator set delta`, `start threshold`, and `Peggy contract code hash`
1. Anyone deploys a Peggy contract using a known codehash and the current validator set of the Cosmos zone to an Ethereum compatible blockchain.
1. Each `Operator` may or may not configure their `Eth Signer` with the above Peggy contract address
1. If configured with an address the `Eth Signer` checks the provided address. If the contract passes validation the `Eth Signer` signs and submits a MsgProposePeggyContract. Validation is defined as finding the correct `Peggy contract code hash` and a validator set matching the current set within `Allowed validator set delta`.
1. A contract address is considered adopted when voting power exceeding the `start threshold` has sent a MsgProposePeggyContract with the same Ethereum address.
1. Because validator sets change quickly, `Eth Signers` not configured with a contract address observe the Cosmos blockchain for submissions. When an address is submitted they validate it and approve it themselves if it passes. This results in a workflow where once a valid contract is proposed it will be ratified in a matter of a few seconds.
1. It is possible for the adoption process to fail if a race condition is intentionally created resulting in less than 66% of the validator power approving more than one valid Peggy Ethereum contract. In this case the Orchestrator will check the contract address with the majority of the power (or at random in the case of a perfect tie) and switch it's vote. This leaves only the possible edge case of >33% of `Operators` intentionally selecting a different contract address. This would be a consensus failure and the bridge can not progress.
1. The bridge ratification process is complete, the contract address is now placed in the store to be referenced and other operations are allowed to move forward.

At this point, we know we have a contract on Ethereum with the proper _MultiSig Set_, that > `start threshold` of the _Orchestrator Set_ is online and agrees with this contract, and that the Cosmos chain has stored this contract address. Only then can we begin to accept transactions to transfer tokens

Note: `start threshold` is some security factor for bootstrapping. 67% is sufficient to release, but we don't want to start until there is a margin of error online (not to fall off with a small change of voting power). This may be 70, 80, 90, or even 95% depending on how much assurances we want that all _Orchestrators_ are operational before starting.

**Comment by jtremback** [comment]
In brokennet, everyone was simply given the address of the correct contract by Justin. They could just trust Justin, or they could check the contract at that address themselves. This is a lot simpler than the above (very elegant) procedure where the validators automatically validate and come to consensus on a contract.

What if we used this simpler procedure in production? We would eliminate several steps:

1. Each `Operator` generates an Ethereum and Cosmos private key for their `EthSigner`. These addresses are signed and submitted by the Operators valoper key in a MsgRegisterEthSigner. The `EthSigner` is now free to use these delegated keys for all Peggy messages.
1. A governance vote is held on bridge parameters including `Peggy ID`
1. Anyone deploys a Peggy contract using a known codehash and the current validator set of the Cosmos zone to an Ethereum compatible blockchain.
1. Each `Operator` may or may not configure their `Eth Signer` with the above Peggy contract address

This would probably have to be done in an upgrade ceremony, but it probably will be anyway.
There is no more explicitly accepted Ethereum address referenced on the Cosmos chain. However, if any events are getting from Ethereum to Cosmos, we know that everyone is looking at the same contract.

The only issue with that I see is that the contract address needs to be conveyed to users and new validators "out of band".

**Comment by jtremback** [comment]
We could add a step 

- Every Eth Signer sends a `MsgSignalPeggyContract`. If 2/3+ of the current valset all have signaled the same contract, a publicly accessible variable `UsingPeggyContract` is set with that address.

This is purely for informational purposes.

**Comment by jtremback** [comment]
I'm proposing the above simpler method on the assumption that the full proposed bootstrapping method is not finished yet. I think that it has the same security as the full method. 

@alpe @jkilpatr do you see any security issues with this? Do you think that it is worth using the simpler method or is the full method already implemented?

**Comment by jkilpatr** [comment]
From a quick reading of the code (by no means complete) it seems we have the voting method behind the bootstrapping already implemented. The goal of having a 'bootstrapping' process at all is to make consensus on which contract and what parameters to use a little less delicate. As once the chain agrees on a set of params everyone can just read them from the chain and there's chance of lets say half of the validators trying to use one contract while the other half try to use another. 

Or just a shorter blocks parameter, lets say half the eth relayers reduce their oracle time to 25 blocks, that's going to cause some sort of problem I'm sure. 

So I think we do need it, but it's thoroughly post MVP and also not really that hard to implement since alpe generalized the voting.

**Comment by jtremback** [comment]
So I guess it's not worth doing any kind of simpler bootstrapping procedure then? I suppose the best thing to do now then is to write integration tests that test the bootstrapping, if it is all supposed to work as designed.

**Comment by jtremback** [comment]
We'll be using the simpler bootstrapping method with manual sharing of the peggy contract address for now.
