### ISSUE TITLE
Remove Cosmos multisig set watching functionality?

### ISSUE THREAD

**Issue by jtremback** [althea-net/peggy#96]
I think we've agreed that the Cosmos module will not actually rely on knowledge of the Peggy.sol contract's current multisig set in https://github.com/althea-net/peggy/issues/70.

If this is still an open question, let me know.

Is it worth removing the functionality that watches it and puts the events into Cosmos? It would result in a simpler codebase, and it's not great having dead code around.

**Comment by jkilpatr** [comment]
@jtremback  is this being done in your pull #92

**Comment by jtremback** [comment]
This was done by #86 which I cherry picked into #92
