### ISSUE TITLE
Possible double spend bug in batches

### ISSUE THREAD

**Issue by jtremback** [althea-net/peggy#99]
I've been doing a review of the attestation Go code in the course of my work on https://github.com/althea-net/peggy/pull/92

As part of this work, I have established that not only do we need to prevent claims that do not increment the nonce (they are duplicates), we also have to prevent claims with nonces that are not contiguous (do not increment the nonce by exactly 1). This is because it is entirely possible, and even likely, for the Cosmos gossip network to deliver messages in a different order than they were sent.

If we do not enforce contiguousness, then a claim with a later nonce could prevent claims with earlier nonces from getting in, if we are requiring that each claim increments the nonce. This is all well and good, and easy enough to implement for deposit claims.

What about batch claims? The nonce on a batch is not designed to be contiguous. When a batch is observed being processed successfully by Ethereum, earlier batches that were not observed have all their transactions released back into the tx pool, to be used in a new batch. So if the Cosmos gossip network delivers two batch claims out of order, the later claim will cause the earlier claim's transactions to be spendable once more, even though the earlier claim was processed by Ethereum. This is a direct double spend bug.

However, we can't require batch nonces to be contiguous, because by their very nature they are not. We could have a special queue on the Eth Signer which would make sure that earlier batch claims were received by Cosmos before trying to submit later ones. This is another piece of code to implement, and is very security critical, as well as being somewhat complicated and non-obvious. There would be nothing in the Cosmos module or the contract preventing double spends, and this makes me nervous.

Another solution would be to have a "processed batch nonce" as well as the normal nonce on batches, but I'm not going to get into that because it's too confusing.

Another alternative is to add a "block claim" with a contiguous nonce (the Eth block height). The block claim would contain all deposit events and batch events from a given Ethereum block. It would use the same attestation voting logic in the Go module that currently exists. It would use the same checks in the Go module to make sure the nonce was only incremented by 1 each time to enforce contiguousness. Once a block attestation was observed, all state changes due to it would be played in at once. I don't think it's much work, and would be a net reduction in code.

This would eliminate any possibility of double spends with batch claims.

**Comment by jtremback** [comment]
Investigating the Eth signer code, it has occurred to me that with the "block claim" system proposed above, there is a hard dependency on batch processed events coming in from Ethereum in their real order. I think this is the case, but if Geth somehow gave the eth signer events in a block out of order, it would result in the same double spend bug.

Also, in the Eth signer, it could be convenient for the programmer to sort an array of claims, due to the way that the events are loaded from geth and then sent to the Peggy Go module. Sorting could be a way to interleave two separate arrays of claims (deposit claims and batch claims), and then separate them into blocks. If the programmer does not use a stable sorting algorithm, this will result in the same double spend bug!! I believe this bug vector also exists on the Go module side, if they were to get sorted again there.

I'd also look at whether there is a possibility of vulnerabilities resulting from deposit claims and batch claims getting out of order. Deposit claims create tokens on the Cosmos side, and batch claims destroy them. I can't think of a vulnerability right now, but it feels like there could be one.

For this reason, I'm not so sure about the wisdom of relying on block heights and stable ordering within blocks of claims to avoid double spends.

The safest thing would be to extend the nonce on the deposit events to cover the batch events as well. Every event that the contract emitted would increment an "event nonce". The Go module would enforce contiguous event nonces, and events would be read into Cosmos state changes ordered by this nonce. Then the security would be under the full control of our code.

**Comment by jtremback** [comment]
@jkilpatr A concise writeup on the batch double spend stuff we discussed today:

- If executed batches are processed out of order by the Cosmos module, this could result in double spends as transactions that had already been spent could be included in a new batch.
- Whatever mechanism we use to prevent this should also be used to prevent duplicate deposit claims, since they are basically the same problem on two different types of events.
- This could be fixed in two ways:
  - Include block height and block index on submitted claims. Check in the Cosmos module that `eventBlockHeight >= lastBlockHeight && eventBlockIndex > lastEventBlockIndex`
    - This does not prevent events from being lost completely, we need another mechanism for that, such as making sure that block heights are contiguous. To implement this, we would need to handle events and claims in blocks and ensure that blocks were contiguous. I won't get into the details, but it is somewhat of a refactor.
  - Extend the nonce we are putting on deposit events in https://github.com/althea-net/peggy/pull/92 to batches as well- this would make it an "event nonce".
    - Basically, there would be a storage slot in the contract containing a Uint256 that would be incremented with every event emitted by the contract. Every event would contain its event nonce. TransactionBatchExecutedEvents would also contain the batch nonce, which we won't cover here.
    - When claims are first received by the Cosmos module, it would check that the event nonce was exactly 1 higher than the last claim submitted by the given Eth Signer. This would ensure that the events were submitted contiguously. My assessment is that this is a smaller refactor at this point.

**Comment by alpe** [comment]
@jtremback you are right that submitting messages to a node not necessarily mean that they go into the blocks in that order. Therefore this scenario exists where claims are processed unordered due to the tx mempool. Good work to raise this issue!

In earlier discussions we had talked about ordered channels. Which means incrementing nonces and no gaps. This would address prevent this scenario and reduce complexity on the happy path. I did not implement it on the cosmos side for the mvp as there was also the idea of rebuilding batches for highest profit that was in the room and not fully clear to me.

To have ordered channels, the nonces need to originate where the process start. For deposits on the ETH side and withdrawals on the the cosmos side.

**Comment by jtremback** [comment]
This has been resolved in https://github.com/althea-net/peggy/pull/92. The way that it is now handled is that the Peggy contract adds an "event nonce" to every event that gets relayed into Cosmos. The Cosmos state machine does not allow a validator to submit claims with non-contiguous event nonces. This ensures that events cannot get out of order. 

Note that this is different than the batch nonce on transaction batches, since this nonce is designed to be non-contiguous.
